development:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_dev
  pool: 5
  username: postgres
  password: 102110

test:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_testing
  pool: 5
  username: postgres
  password: 102110

production:
  adapter: postgresql
  encoding: unicode
  database: hello_rails_productioning
  pool: 5
  username: postgres
  password: 102110
